#!/usr/bin/env bash
# Install the `bh` command.
#
# Two ways to get an interpreter, in order of preference:
#
#   1. uv provisions one. The distro's Python then stops deciding what syntax
#      this codebase may use — Ubuntu 22.04 ships 3.10, 24.04 ships 3.12, and
#      writing for the oldest of them is how a `datetime.UTC` import once made
#      every command fail on 22.04. Needs network on first install only.
#   2. The system python3, if it is new enough. Nothing to download, and the
#      version check below fails with a sentence rather than an ImportError
#      from inside the stdlib.
#
# A dedicated virtualenv is created either way. Every entry point — brainhub.py,
# brainhub_engine.py and serve.py — imports markdown-it-py through
# brainhub_core.markdown, so none of them runs on a bare interpreter. (The
# README claimed otherwise for a long time; running the CLI on a clean
# interpreter is what showed it.) The env is BrainHub's own, never the system
# site-packages.
#
# Usage: ./install.sh [--system-python] [--bin-dir DIR] [--venv DIR]
set -euo pipefail

PINNED_PYTHON="3.12"   # what the uv path provisions
MINIMUM_PYTHON="3.10"  # what the system path accepts; keep in sync with _python_check.py
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
VENV_DIR="${HOME}/.local/share/brainhub/venv"
FORCE_SYSTEM=0

while [ $# -gt 0 ]; do
  case "$1" in
    --system-python) FORCE_SYSTEM=1; shift ;;
    --bin-dir) BIN_DIR="$2"; shift 2 ;;
    --venv) VENV_DIR="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

# Resolve the interpreter to bake into the wrapper.
PYTHON=""
if [ "$FORCE_SYSTEM" -eq 0 ] && command -v uv >/dev/null 2>&1; then
  echo "==> uv found; provisioning Python ${PINNED_PYTHON}"
  uv python install "$PINNED_PYTHON" >&2
  # Resolved from a neutral directory, with VIRTUAL_ENV cleared. `uv python
  # find` prefers a .venv discovered from the working directory — and
  # --no-project does not stop it, because that flag only suppresses reading
  # pyproject.toml. Run inside a checkout it therefore returns the DEVELOPMENT
  # virtualenv, and baking that into the wrapper points the installed command
  # at a directory that gets deleted and rebuilt.
  PYTHON="$(cd / && env -u VIRTUAL_ENV uv python find --managed-python --no-project "$PINNED_PYTHON")"
else
  if [ "$FORCE_SYSTEM" -eq 0 ]; then
    echo "==> uv not found; falling back to the system python3" >&2
    echo "    (install uv for a pinned interpreter: curl -LsSf https://astral.sh/uv/install.sh | sh)" >&2
  fi
  PYTHON="$(command -v python3 || true)"
  if [ -z "$PYTHON" ]; then
    echo "no python3 on PATH, and no uv to provision one" >&2
    exit 1
  fi
fi

# Verify before writing a wrapper: a version failure discovered here names the
# problem, whereas one discovered on first run surfaces as an import error deep
# in the stdlib.
if ! "$PYTHON" -c "import sys; raise SystemExit(0 if sys.version_info >= tuple(int(p) for p in '${MINIMUM_PYTHON}'.split('.')) else 1)"; then
  RUNNING="$("$PYTHON" -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')"
  cat >&2 <<EOF
${PYTHON} is Python ${RUNNING}; BrainHub needs ${MINIMUM_PYTHON} or newer.

Install uv and re-run, which provisions ${PINNED_PYTHON} without touching the
system Python or needing root:

  curl -LsSf https://astral.sh/uv/install.sh | sh
  ./install.sh
EOF
  exit 1
fi

# Dedicated environment, so BrainHub's dependencies never touch system
# site-packages and an OS upgrade cannot take them away.
echo "==> creating environment: $VENV_DIR"
rm -rf "$VENV_DIR"
if command -v uv >/dev/null 2>&1; then
  uv venv --python "$PYTHON" "$VENV_DIR" >&2
  VIRTUAL_ENV="$VENV_DIR" uv pip install --quiet "$ROOT/mcp_package" >&2
else
  "$PYTHON" -m venv "$VENV_DIR"
  "$VENV_DIR/bin/python" -m pip install --quiet --disable-pip-version-check "$ROOT/mcp_package" >&2
fi
VENV_PYTHON="$VENV_DIR/bin/python"

# Confirm it actually runs this tree. Checking the version number alone is what
# let "standard library only" stand while all three entry points imported
# markdown-it-py: the claim only fails on an interpreter that lacks it.
"$VENV_PYTHON" "$ROOT/brainhub.py" --help >/dev/null

mkdir -p "$BIN_DIR"
WRAPPER="$BIN_DIR/bh"
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Generated by BrainHub install.sh — re-run it to repoint at another interpreter.
exec "${VENV_PYTHON}" "${ROOT}/brainhub.py" "\$@"
EOF
chmod +x "$WRAPPER"

echo "==> installed: $WRAPPER"
echo "    interpreter: $VENV_PYTHON ($("$VENV_PYTHON" -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'))"
case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *) echo "    note: ${BIN_DIR} is not on PATH; add it to use \`bh\` directly" ;;
esac
