#!/usr/bin/env bash
# Install the `bh` command.
#
# uv provisions the interpreter. That is the whole point: the distribution's
# Python otherwise decides what syntax this codebase may use — Ubuntu 22.04
# ships 3.10, 24.04 ships 3.12 — and writing for the oldest of them is how a
# `datetime.UTC` import once made every command fail on 22.04. Pinning our own
# removes the question. Needs network on first install only.
#
# There is deliberately no system-python fallback. Supporting one means every
# line of this codebase must keep working on whatever the oldest supported
# distribution ships, which is a permanent tax paid by every future change.
#
# A dedicated virtualenv holds the dependencies. Every entry point —
# brainhub.py, brainhub_engine.py and serve.py — imports markdown-it-py through
# brainhub_core.markdown, so none of them runs on a bare interpreter. (The
# README claimed otherwise for a long time; running the CLI on a clean
# interpreter is what showed it.) The env is BrainHub's own, never the system
# site-packages.
#
# Usage: ./install.sh [--bin-dir DIR] [--venv DIR] [--python VERSION]
set -euo pipefail

PINNED_PYTHON="3.12"   # keep in sync with _python_check.py's MINIMUM
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
VENV_DIR="${HOME}/.local/share/brainhub/venv"

while [ $# -gt 0 ]; do
  case "$1" in
    --bin-dir) BIN_DIR="$2"; shift 2 ;;
    --venv) VENV_DIR="$2"; shift 2 ;;
    --python) PINNED_PYTHON="$2"; shift 2 ;;
    -h|--help) sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

# uv is required. Failing here with the install line beats failing later with
# a version error the reader has to diagnose.
if ! command -v uv >/dev/null 2>&1; then
  cat >&2 <<'EOF'
BrainHub's installer needs uv, which provisions its own Python without root
and without touching the system one:

  curl -LsSf https://astral.sh/uv/install.sh | sh

then re-run ./install.sh
EOF
  exit 1
fi

echo "==> provisioning Python ${PINNED_PYTHON}"
uv python install "$PINNED_PYTHON" >&2
# Resolved from a neutral directory, with VIRTUAL_ENV cleared. `uv python find`
# prefers a .venv discovered from the working directory — and --no-project does
# not stop it, because that flag only suppresses reading pyproject.toml. Run
# inside a checkout it therefore returns the DEVELOPMENT virtualenv, and baking
# that into the wrapper points the installed command at a directory that gets
# deleted and rebuilt.
PYTHON="$(cd / && env -u VIRTUAL_ENV uv python find --managed-python --no-project "$PINNED_PYTHON")"

# Dedicated environment, so BrainHub's dependencies never touch system
# site-packages and an OS upgrade cannot take them away.
echo "==> creating environment: $VENV_DIR"
rm -rf "$VENV_DIR"
uv venv --python "$PYTHON" "$VENV_DIR" >&2
VIRTUAL_ENV="$VENV_DIR" uv pip install --quiet "$ROOT/mcp_package" >&2
VENV_PYTHON="$VENV_DIR/bin/python"

# Confirm it actually runs this tree. Checking the version number alone is what
# let "standard library only" stand while all three entry points imported
# markdown-it-py: the claim only fails on an interpreter that lacks it.
"$VENV_PYTHON" "$ROOT/brainhub.py" --help >/dev/null

mkdir -p "$BIN_DIR"
WRAPPER="$BIN_DIR/bh"
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Generated by BrainHub install.sh — re-run it to repoint at another interpreter.
exec "${VENV_PYTHON}" "${ROOT}/brainhub.py" "\$@"
EOF
chmod +x "$WRAPPER"

echo "==> installed: $WRAPPER"
echo "    interpreter: $VENV_PYTHON ($("$VENV_PYTHON" -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'))"
case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *) echo "    note: ${BIN_DIR} is not on PATH; add it to use \`bh\` directly" ;;
esac
