"""Dashboard render components — a status board that advertises its own age.

Why this module exists: the company status board used to be a hand-authored
HTML artifact regenerated by whoever remembered to. It sat five days stale with
the old date still printed inside it, and nothing about the page said so. A
stale dashboard that *looks* fresh is worse than no dashboard: it is read as
current and acted on. So the components here are built around one rule —

    the page always states how old its data is, and shouts when that is old.

Everything is a pure function returning an HTML string, in the shape of
``web_layout.render_stat_grid``: text in, escaped markup out, no I/O, no
globals. Colour comes only from the CSS custom properties defined in
``web_assets`` (``--surface``, ``--border``, ``--caution*``, ``--ok*``,
``--accent*``, ``--muted``, ``--text``, ``--chip-bg``), never a literal hex, so
a board inherits light/dark and any brand retheme for free. ``test_serve_
dashboard`` fails the build if a ``#rrggbb`` ever appears in ``DASHBOARD_CSS``.

STRUCTURE COMES FROM daisyUI, COLOUR STILL COMES FROM THE BRAND
--------------------------------------------------------------
The components are daisyUI's — ``alert`` for the banner, ``stats``/``stat`` for
the tiles, ``card`` for each priority group — and every class name is imported
from ``ui_classes`` rather than typed, so the build can see it and the collision
test can tell adoption apart from an accident.

What is deliberately NOT taken from daisyUI is the palette. Its ``alert-warning``
paints a full-saturation ``--color-warning`` fill with ``--color-warning-content``
text over it; measured on this shell that is dark orange on bright orange, and
the banner it produces is louder and harder to read than the tinted one this
board already had. So the component is driven through its OWN variables —
``--alert-color`` / ``--alert-border-color`` — with brand caution tokens. That is
adoption, not override: daisyUI still does the painting, it is simply told which
colours to paint with, and a future retheme still reaches it.

One thing to know before adding a component here: the shell opens with an
unlayered ``* { padding: 0 }``, which beats every layered daisyUI padding rule.
``web_assets._BRAND_UI_CSS`` restores it for the components in use — a new one
needs a line there or it arrives flat.

TWO THINGS THE BOARD COULD NOT SAY, AND NOW CAN
-----------------------------------------------
1. **"Better or worse than last week."** The board had no time dimension at all
   — measured, not assumed: a grep for trend / ↑ / ↓ / 比上週 returned nothing.
   :func:`render_trend_section` draws it with ``vendor/report_chart.line``, the
   in-house primitive (self-contained SVG, own ``<style>``, no JS, no CDN), and
   :func:`render_delta` puts the change against the previous snapshot on each
   tile. The data those two consume comes from :mod:`dashboard_history`; nothing
   in here touches disk.
2. **"What we do not know."** :func:`render_bounds_section` — the honest-limits
   card. A board that lists only what it measured implies it measured
   everything, because there is no row shape that can represent an unmeasured
   fact. Structure borrowed from the report library (``.bounds`` + the
   three-state ``.verify`` card); its CSS deliberately NOT borrowed, that is
   warm-paper print media and this is the brand's screen palette.
"""
from __future__ import annotations

import html
from collections.abc import Mapping, Sequence
from datetime import datetime, timedelta, timezone

from .ui_classes import (
    ALERT,
    ALERT_WARNING,
    CARD,
    CARD_BODY,
    CARD_TITLE,
    STAT,
    STAT_TITLE,
    STAT_VALUE,
    STATS,
)
from .render import chart_primitives as _rc


# A day and a half of silence is the point where "nobody updated it yet today"
# turns into "nobody is updating this". Chosen to survive one skipped workday
# and flag two.
STALE_AFTER_HOURS = 48

# Tone -> modifier class. The names are the *meaning* (ok / caution), not the
# colour, because the colour is the theme's job. Any unknown tone degrades to
# neutral rather than raising: a dashboard must render.
TONE_CLASSES = {
    "neutral": "dash-tone-neutral",
    "ok": "dash-tone-ok",
    "caution": "dash-tone-caution",
    "accent": "dash-tone-accent",
}

# The item states the data file may use, and how each reads on the page.
STATE_TONES = {"blocked": "caution", "active": "accent", "done": "ok"}
STATE_LABELS = {"blocked": "卡住", "active": "進行中", "done": "已收"}

# The honest-boundary states. Modelled on the report library's three-state
# verification card (tenants/.claude/skills/aw-report-style, 卡 K + 驗證狀態卡):
# "we measured it", "we did not measure it", and "something stopped us" are three
# different facts, and the last two mean opposite things to a reader — collapsing
# them lets "we are blind here" be read as "nothing to see".
#
# An unrecognised state degrades to UNMEASURED, never to measured. This section
# exists to stop the board from over-claiming; a typo must not be able to promote
# an entry into "已量測".
BOUND_STATES = {
    "measured": ("已量測", "ok"),
    "unmeasured": ("未量測", "neutral"),
    "blocked": ("被擋", "caution"),
    # The Chinese labels are accepted as input too, so a human editing the JSON
    # can write what they see on the page.
    "已量測": ("已量測", "ok"),
    "未量測": ("未量測", "neutral"),
    "被擋": ("被擋", "caution"),
}
BOUND_DEFAULT_STATE = "unmeasured"


def _tone_class(tone: object) -> str:
    return TONE_CLASSES.get(str(tone or "neutral"), TONE_CLASSES["neutral"])


def parse_timestamp(value: object) -> datetime | None:
    """An ISO-8601 stamp as an aware UTC datetime, or None when unreadable.

    Naive stamps are read as UTC and a trailing ``Z`` is accepted, matching
    ``memory._memory_date``. None is a real answer here — an unreadable
    ``updated_at`` makes the banner warn rather than quietly claim freshness.
    """
    text = str(value or "").strip().strip('"')
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        try:
            parsed = datetime.fromisoformat(f"{text}T00:00:00+00:00")
        except ValueError:
            return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def humanize_age(age: timedelta) -> str:
    """"3 天前" / "5 小時前" — coarse on purpose; this is a staleness cue."""
    seconds = max(0, int(age.total_seconds()))
    days, rest = divmod(seconds, 86400)
    hours = rest // 3600
    if days:
        return f"{days} 天前"
    if hours:
        return f"{hours} 小時前"
    return "剛剛"


def render_staleness_banner(
    updated_at: object,
    *,
    now: datetime | None = None,
    stale_after_hours: int = STALE_AFTER_HOURS,
) -> str:
    """The banner that stops the page from lying about being current.

    ``data-stale`` is the machine-readable verdict — ``yes`` / ``no`` /
    ``unknown`` — so a test (and a future health check) can assert on the
    judgement rather than on prose. An unparseable or missing stamp is
    ``unknown`` and warns: not knowing the age is not evidence of freshness.
    """
    moment = now or datetime.now(timezone.utc)
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    stamp = parse_timestamp(updated_at)

    if stamp is None:
        return (
            f'<div class="{ALERT_WARNING} dash-stale dash-stale--warn"'
            ' data-stale="unknown" role="status">'
            "<strong>⚠ 這份資料沒有可判讀的更新時間</strong>"
            '<span class="dash-stale-detail">看不出多舊 ⇒ 一律當可能過期看待。'
            "資料檔需要 <code>updated_at</code>（ISO-8601）。</span>"
            "</div>"
        )

    age = moment - stamp
    shown = html.escape(stamp.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
    ago = html.escape(humanize_age(age))
    if age >= timedelta(hours=stale_after_hours):
        days = max(1, int(age.total_seconds() // 86400))
        return (
            f'<div class="{ALERT_WARNING} dash-stale dash-stale--warn"'
            ' data-stale="yes" role="status">'
            f"<strong>⚠ 這份資料可能已過期 · 已 {days} 天沒更新</strong>"
            f'<span class="dash-stale-detail">最後更新 {shown}（{ago}）·'
            f" 超過 {stale_after_hours} 小時未更新，請先確認再據以決策。</span>"
            "</div>"
        )
    # The calm state takes the BARE alert, not `alert-info`: a fresh board is
    # the answer nobody has to act on, and giving it a saturated fill would put
    # it at the same volume as the warning it alternates with.
    return (
        f'<div class="{ALERT} dash-stale dash-stale--fresh"'
        ' data-stale="no" role="status">'
        f"<strong>資料為新</strong>"
        f'<span class="dash-stale-detail">最後更新 {shown}（{ago}）</span>'
        "</div>"
    )


def render_delta(delta: object) -> str:
    """"↑1" / "↓2" / "→0" — or the empty string when there is no baseline.

    ``delta is None`` is the load-bearing case and it renders NOTHING. Without a
    previous snapshot the honest statement is "we cannot say", and the one thing
    that must not appear is a reassuring ±0: "no change" is a measurement, and
    printing it from no measurement is the same class of lie as a stale board
    printing a fresh date. ``0`` with a real baseline behind it does render, as
    ``→0`` — that one IS a measurement.

    ``data-delta`` carries the signed number so a test (or a health check) can
    assert on the judgement rather than on an arrow glyph.
    """
    if delta is None:
        return ""
    try:
        number = float(delta)
    except (TypeError, ValueError):
        return ""
    if number == int(number):
        number = int(number)
    arrow = "↑" if number > 0 else ("↓" if number < 0 else "→")
    signed = f"+{number}" if number > 0 else str(number)
    shown = f"{arrow}{abs(number)}"
    direction = "up" if number > 0 else ("down" if number < 0 else "flat")
    return (
        f'<span class="dash-kpi-delta dash-delta-{direction}"'
        f' data-delta="{html.escape(signed, quote=True)}">{html.escape(shown)}</span>'
    )


def render_kpi_tile(
    label: object,
    value: object,
    tone: str = "neutral",
    delta: object = None,
) -> str:
    """One stat tile: the number first, the label under it, the change under that.

    daisyUI's ``stat`` trio. ``stat-value`` / ``stat-title`` bring the size pair
    (24px over 12px muted) that used to be hand-typed here; the ``dash-*`` names
    stay alongside them as the hooks the tone colours and the tests hang off —
    ``stat-value`` is shared with every other stat on the site and is not a
    place to attach "this KPI is the blocked one".

    ``delta`` is optional and defaults to None, which renders no third line at
    all. The line is NOT daisyUI's ``stat-desc``: that class is absent from the
    vendored build (see ``ui_classes``), and adding it would need an npm rebuild
    rather than a code change.
    """
    return (
        f'<div class="{STAT} dash-kpi {_tone_class(tone)}">'
        f'<span class="{STAT_VALUE} dash-kpi-value">{html.escape(str(value))}</span>'
        f'<span class="{STAT_TITLE} dash-kpi-label">{html.escape(str(label))}</span>'
        f"{render_delta(delta)}"
        "</div>"
    )


def render_kpi_row(tiles: Sequence[str]) -> str:
    """Grid wrapper for ``render_kpi_tile`` output (empty in -> empty out).

    daisyUI's ``stats`` is a single scrolling row. Eight tiles in one row is a
    horizontal scrollbar on a laptop and an eight-storey column on a phone, so
    the CSS re-points its grid to wrap (2 up on a phone, 5 up from 640px) and
    keeps everything else the component brings: the box, the radius, the
    dividers between tiles.
    """
    if not tiles:
        return ""
    return f'<div class="{STATS} dash-kpis">{"".join(tiles)}</div>'


def render_status_item(
    text: object,
    owner: object = "",
    state: object = "",
    note: object = "",
    *,
    href: str = "",
) -> str:
    """One row in a section: what it is, who holds it, where it stands.

    ``href`` is optional and exists for mechanically derived rows that can
    point at the real surface (an open decision board). Hand-written data does
    not have to supply it.
    """
    state_key = str(state or "").strip().lower()
    tone = STATE_TONES.get(state_key, "neutral")
    label = STATE_LABELS.get(state_key, str(state or "").strip())

    title = html.escape(str(text or "").strip() or "（未命名項）")
    if href:
        title = f'<a class="dash-item-link" href="{html.escape(href, quote=True)}">{title}</a>'

    chips = []
    if label:
        chips.append(f'<span class="dash-chip {_tone_class(tone)}">{html.escape(label)}</span>')
    owner_text = str(owner or "").strip()
    if owner_text:
        chips.append(f'<span class="dash-chip dash-chip-owner">{html.escape(owner_text)}</span>')
    chips_html = f'<div class="dash-chips">{"".join(chips)}</div>' if chips else ""

    note_text = str(note or "").strip()
    note_html = f'<div class="dash-item-note">{html.escape(note_text)}</div>' if note_text else ""

    return (
        f'<div class="dash-item dash-item--{html.escape(tone, quote=True)}">'
        f'<div class="dash-item-main"><div class="dash-item-title">{title}</div>{note_html}</div>'
        f"{chips_html}"
        "</div>"
    )


def render_priority_section(
    title: object,
    subtitle: object = "",
    items: Sequence[Mapping[str, object]] | None = None,
) -> str:
    """A P0/P1/P2/P3 grouping.

    ``items`` are plain mappings (``text`` / ``owner`` / ``state`` / ``note`` /
    optional ``href``) rendered through ``render_status_item``, so a caller
    hands over data and never assembles markup. An empty section still renders
    — "P0 is empty" is information, and a section that vanishes reads as a
    section nobody filled in.
    """
    rows = []
    for item in items or ():
        if not isinstance(item, Mapping):
            continue
        rows.append(render_status_item(
            item.get("text"),
            item.get("owner", ""),
            item.get("state", ""),
            item.get("note", ""),
            href=str(item.get("href") or ""),
        ))
    body = "".join(rows) or '<p class="dash-empty-row">（本區目前沒有項目）</p>'
    subtitle_text = str(subtitle or "").strip()
    subtitle_html = (
        f'<span class="dash-section-sub">{html.escape(subtitle_text)}</span>'
        if subtitle_text else ""
    )
    return (
        f'<section class="{CARD} dash-section">'
        f'<div class="{CARD_BODY} dash-section-body">'
        f'<h2 class="{CARD_TITLE} dash-section-head">'
        f'{html.escape(str(title or "").strip() or "（未命名區）")}'
        f"{subtitle_html}</h2>"
        f'<div class="dash-items">{body}</div>'
        "</div></section>"
    )


def _trend_placeholder(state: str, headline: str, detail: str) -> str:
    """The not-a-chart. Deliberately a bare ``alert``, not an empty plot frame.

    An axis box with one dot in it reads as "the metric is flat"; the point of
    this branch is that we have nothing to say yet, and saying nothing has to
    look different from saying zero.
    """
    return (
        f'<div class="{ALERT} dash-trend-empty" data-trend="{html.escape(state, quote=True)}"'
        ' role="status">'
        f"<strong>{html.escape(headline)}</strong>"
        f'<span class="dash-trend-detail">{html.escape(detail)}</span>'
        "</div>"
    )


# How many categorical slots report_chart cycles through before wrapping. The
# legend has to wrap at the same number or a 9th line's swatch would name the
# wrong colour.
_CHART_SLOTS = 8


def _trend_legend(series: Sequence[Mapping[str, object]]) -> str:
    """Swatch + name per line, in the primitive's own slot order.

    ``report_chart.line`` direct-labels each line at its endpoint, which is the
    better technique and is what the dataviz guidance asks for — right up until
    two series END ON THE SAME VALUE. Measured on the first real render: P1 and
    P2 both finished at 4, the two labels landed on identical coordinates, and
    what shipped was one smudged label and one series with no identity at all.
    Small-integer count data ties constantly, so this is the normal case, not an
    edge case.

    The primitive cannot be fixed from here (vendored, byte-compared against the
    catalog SSoT), so identity gets a second, non-overlapping channel. The
    endpoint labels still carry the values; this only carries which line is
    which. Slot classes rather than inline styles, so the colours stay in the
    stylesheet with everything else.
    """
    chips = []
    for index, entry in enumerate(series):
        slot = (index % _CHART_SLOTS) + 1
        name = str(entry.get("name") or f"series {index + 1}")
        chips.append(
            f'<span class="dash-trend-key">'
            f'<i class="dash-trend-swatch dash-trend-swatch-{slot}"></i>'
            f"{html.escape(name)}</span>"
        )
    return f'<div class="dash-trend-legend">{"".join(chips)}</div>' if chips else ""


def render_trend_section(
    series: Sequence[Mapping[str, object]] | None,
    x_labels: Sequence[object] | None,
    *,
    omitted: Sequence[object] = (),
    title: str = "📈 趨勢 · P0–P3 與待決策",
    history_hint: str = "",
) -> str:
    """The time dimension — the board's single biggest gap before this existed.

    Drawn with ``report_chart.line`` (the in-house primitive, SSoT in
    lab/catalog): self-contained SVG with its own ``<style>``, no JS, no CDN,
    light+dark aware. That is not a stylistic choice — BrainHub artifacts must be
    one file that opens anywhere, so a chart library was never on the table.

    Three outcomes, and the two quiet ones are the ones that matter:

    * ``data-trend="none"`` — no history file yet. Says so.
    * ``data-trend="insufficient"`` — one point, or nothing drawable. A one-point
      "line" is a dot the reader interprets as a flat trend; it is refused.
    * ``data-trend="ok"`` — two or more points, chart rendered.

    ``omitted`` names keys that could not be drawn because some point in the
    window does not carry them. They are printed rather than dropped silently:
    four series where five were asked for is a fact about the data, and a chart
    that quietly renders fewer lines looks exactly like a chart that had fewer
    lines to draw.
    """
    labels = list(x_labels or ())
    rows = [s for s in (series or ()) if isinstance(s, Mapping)]
    hint = str(history_hint or "").strip()

    if not labels:
        body = _trend_placeholder(
            "none",
            "尚無歷史 · 這一區還畫不出趨勢",
            "第一個點會在下次資料更新時自動寫入" + (f"（{hint}）" if hint else "")
            + "；有兩個點以後這裡才會出現折線。",
        )
    elif len(labels) < 2:
        body = _trend_placeholder(
            "insufficient",
            f"只有 {len(labels)} 個歷史點 · 還不足以說「比上週好或壞」",
            "趨勢至少要兩個點。這裡刻意不畫單點折線——一個點的線會被讀成「持平」，"
            "但我們量到的是「還沒有比較對象」。",
        )
    elif not rows:
        body = _trend_placeholder(
            "insufficient",
            f"有 {len(labels)} 個歷史點，但沒有一條數列在每個點都存在",
            "只在部分快照出現的欄位不會被補 0 畫出來——那個 0 是我們沒量到的，"
            "跟真的歸零長得一模一樣。",
        )
    else:
        try:
            svg = _rc.line(rows, labels, title="P0–P3 · 待決策（件數）")
        except Exception as exc:  # noqa: BLE001 - a dashboard must render
            body = _trend_placeholder(
                "insufficient",
                "趨勢圖畫不出來",
                f"歷史資料有 {len(labels)} 個點，但繪圖器拒絕了它：{exc}",
            )
        else:
            body = (
                f'<div class="dash-trend" data-trend="ok">{svg}'
                f"{_trend_legend(rows)}</div>"
            )

    notes = []
    if labels:
        notes.append(f"{len(labels)} 個快照 · {labels[0]} → {labels[-1]}")
    dropped = [str(key) for key in omitted if str(key).strip()]
    if dropped:
        notes.append("缺歷史資料、未畫：" + "、".join(dropped))
    subtitle = " · ".join(notes)
    subtitle_html = (
        f'<span class="dash-section-sub">{html.escape(subtitle)}</span>' if subtitle else ""
    )
    return (
        f'<section class="{CARD} dash-section dash-trend-section">'
        f'<div class="{CARD_BODY} dash-section-body">'
        f'<h2 class="{CARD_TITLE} dash-section-head">{html.escape(title)}{subtitle_html}</h2>'
        f"{body}"
        "</div></section>"
    )


def render_bounds_section(
    entries: Sequence[Mapping[str, object]] | None,
    *,
    title: str = "🔍 這塊板子的邊界 · 我們不知道什麼",
    subtitle: str = "已量測 / 未量測 / 被擋 —— 後兩者意思相反，分開寫",
) -> str:
    """What the board does NOT know, stated on the board.

    RATIONALE, kept here because it is the whole reason the section exists: a
    dashboard that shows only what it knows implies it knows everything. Every
    number above this card is a thing somebody measured; nothing above it can
    represent a thing nobody measured, so the absence of a row reads as the
    absence of a problem. The unmeasured column is the point.

    The information structure is the report library's (``.bounds`` honest-limit
    card + the three-state ``.verify`` card, tenants/.claude/skills/
    aw-report-style). ONLY the structure: that catalog is print media on a warm
    paper palette, and its CSS on this shell would be a second palette competing
    with the brand tokens. The components here are the same daisyUI card/alert
    and the same ``dash-*`` tone classes as the rest of the board.

    An empty list still renders the card, and says the card is empty. A section
    that vanishes when nobody filled it in is indistinguishable from a board
    with no blind spots — which is the exact misreading this is built to stop.
    """
    rows: list[str] = []
    for entry in entries or ():
        if not isinstance(entry, Mapping):
            continue
        fact = str(entry.get("fact") or entry.get("text") or "").strip()
        if not fact:
            continue
        raw_state = str(entry.get("state") or "").strip()
        label, tone = BOUND_STATES.get(raw_state, BOUND_STATES[BOUND_DEFAULT_STATE])
        state_key = raw_state.lower() if raw_state.lower() in BOUND_STATES else BOUND_DEFAULT_STATE
        detail = str(entry.get("detail") or entry.get("note") or "").strip()
        if not detail and label == "被擋":
            # Blocked without a reason is not an honest boundary, it is a shrug.
            detail = "（未註明被什麼擋住——這一格還沒講清楚）"
        detail_html = (
            f'<div class="dash-bound-detail">{html.escape(detail)}</div>' if detail else ""
        )
        rows.append(
            f'<div class="dash-bound dash-bound--{html.escape(tone, quote=True)}"'
            f' data-bound-state="{html.escape(state_key, quote=True)}">'
            f'<span class="dash-chip {_tone_class(tone)} dash-bound-tag">{html.escape(label)}</span>'
            f'<div class="dash-bound-main">'
            f'<div class="dash-bound-fact">{html.escape(fact)}</div>{detail_html}'
            "</div></div>"
        )

    body = "".join(rows) or (
        '<p class="dash-empty-row">（這一區沒有項目——代表沒人填，不代表沒有盲區）</p>'
    )
    return (
        f'<section class="{CARD} dash-section dash-bounds-section">'
        f'<div class="{CARD_BODY} dash-section-body">'
        f'<h2 class="{CARD_TITLE} dash-section-head">{html.escape(title)}'
        f'<span class="dash-section-sub">{html.escape(subtitle)}</span></h2>'
        f'<div class="dash-bounds">{body}</div>'
        f'<div class="{ALERT} dash-bounds-close">'
        "把沒量到的格子框出來，量到的那些才可信——這一區不是免責，"
        "是讓你知道哪些數字可以直接用、哪些要等補齊再下判斷。"
        "</div>"
        "</div></section>"
    )


def render_empty_state(data_path: object, reason: str = "") -> str:
    """Shown when the data file is missing or unreadable — a next step, not a 500."""
    reason_html = (
        f'<p class="dash-empty-reason">{html.escape(reason)}</p>' if reason else ""
    )
    return (
        f'<section class="{CARD} dash-empty">'
        f'<div class="{CARD_BODY}">'
        "<h2>還沒有資料檔</h2>"
        f"{reason_html}"
        "<p>這頁從一個 JSON 檔渲染。建立它就會有內容：</p>"
        f"<pre><code>{html.escape(str(data_path))}</code></pre>"
        "<pre><code>"
        + html.escape(
            '{\n'
            '  "updated_at": "2026-08-02T12:00:00+08:00",\n'
            '  "title": "aworkr · 公司狀況 SPoG",\n'
            '  "sections": [\n'
            '    {"id": "P0", "title": "P0 · 掉下來就出事", "subtitle": "時效",\n'
            '     "items": [{"text": "…", "owner": "owner", "state": "blocked", "note": "…"}]}\n'
            '  ]\n'
            '}'
        )
        + "</code></pre>"
        "<p class=\"dash-empty-reason\">下方「待決策」區不吃這個檔——它直接讀 decisions/，"
        "所以那一段不會過期。</p>"
        "</div></section>"
    )


# Scoped to `.dash-*`; every colour is a token from web_assets' CSS variables so
# the board follows the theme. No literal hex here — the test asserts it.
#
# This block sits in the BODY, after the three stylesheets in <head>. Both facts
# matter: it is unlayered (so it outranks daisyUI's component rules, which are
# all inside `@layer`) and it is last (so it wins ties against the shell's own
# unlayered rules). That is the whole reason a handful of declarations can
# re-dress a daisyUI component without touching the vendored file.
#
# Where a daisyUI component exposes a variable, the variable is what gets set —
# `--alert-color` rather than `background`. Overriding the output would win the
# same argument today and lose it the moment daisyUI paints that surface from
# somewhere else; setting the input keeps the component in charge.
DASHBOARD_CSS = (
    "<style>"
    # ── Staleness banner = `.alert`. It brings the box, the radius and the
    #    border machinery; the brand supplies the colours.
    #
    #    TWO of daisyUI's layout defaults have to be turned off, and the second
    #    one is invisible until you count the children. `.alert` sets
    #    `grid-auto-flow: column`, so the headline and the detail sit side by
    #    side. Setting the flow back to `row` alone does NOT fix it: daisyUI also
    #    ships `.alert:has(:nth-child(2)) { grid-template-columns: auto minmax(
    #    auto,1fr) }` — a two-child alert is assumed to be icon + message, and
    #    two explicit columns keep the pair on one line whatever the flow says.
    #    Measured (getComputedStyle on the served page): flow `row`, columns
    #    `293px 756px`. So the column track is pinned to one, explicitly.
    ".dash-stale{grid-auto-flow:row;grid-template-columns:minmax(0,1fr);"
    "justify-items:start;gap:4px;margin:14px 0 20px;}"
    ".dash-stale-detail{font-size:0.88rem;color:var(--muted);}"
    # --alert-color is the fill, --alert-border-color the edge. Giving them
    # different values is what makes the border visible at all (see the note in
    # web_assets._BRAND_UI_CSS); the 5px inline-start bar is the brand's own
    # severity cue, kept from the hand-written version.
    ".dash-stale--warn{--alert-color:var(--caution-bg);"
    "--alert-border-color:var(--caution-border);color:var(--caution-fg);"
    "border-inline-start:5px solid var(--caution);}"
    ".dash-stale--warn strong{color:var(--caution-fg);font-size:1.05rem;}"
    ".dash-stale--warn .dash-stale-detail{color:var(--caution-fg);}"
    ".dash-stale--fresh{--alert-color:var(--surface);--alert-border-color:var(--border);"
    "border-inline-start:5px solid var(--ok);}"
    ".dash-stale--fresh strong{color:var(--ok-fg);}"
    # ── KPI row = `.stats` + `.stat`. daisyUI's stats is one scrolling row;
    #    re-pointed to a wrapping grid so eight tiles read as a block rather
    #    than as a scrollbar. `overflow:visible` undoes the scroll container.
    ".dash-kpis{display:grid;grid-auto-flow:row;grid-template-columns:repeat(2,1fr);"
    "overflow:visible;margin:0 0 22px;}"
    # Dividers are drawn from scratch rather than inherited, and the reason is
    # that daisyUI's own divider logic is keyed to ITS layout: `stats-vertical`
    # gives every tile but the last a bottom edge, `sm:stats-horizontal` swaps
    # that for a trailing edge. Re-pointed to a wrapping grid, neither describes
    # where the tiles actually are — measured at 390px, tile 7 of 8 carried a
    # bottom border and tile 8 did not, i.e. a rule under half of the last row.
    # So daisyUI's block-end divider is switched off and both axes are drawn
    # against the grid's real geometry: the trailing edge on every tile that is
    # not last in its row, the leading edge on every tile that is not in row one.
    ".dash-kpi{padding:14px 12px;border-block-end:none;}"
    ".dash-kpi:not(:last-child){border-inline-end:1px dashed var(--border);}"
    ".dash-kpi:nth-child(2n){border-inline-end:none;}"
    ".dash-kpi:nth-child(n+3){border-block-start:1px dashed var(--border);}"
    ".dash-kpi-value{line-height:1.15;color:var(--text);}"
    ".dash-kpi-label{text-align:center;}"
    ".dash-kpi.dash-tone-caution .dash-kpi-value{color:var(--caution-fg);}"
    ".dash-kpi.dash-tone-ok .dash-kpi-value{color:var(--ok-fg);}"
    ".dash-kpi.dash-tone-accent .dash-kpi-value{color:var(--accent);}"
    # ── Each priority group = `.card`. The card is now the bounded object, so
    #    the rows inside it give up their own boxes: a border inside a border
    #    inside a border is three competing edges and no hierarchy. What the
    #    rows keep is the one thing that carries meaning — the state-coloured
    #    bar on the leading edge.
    ".dash-section{margin:0 0 16px;}"
    ".dash-section-body{gap:2px;}"
    # Layout only. The size/spacing/border-suppression this used to repeat now
    # lives on `.card-title` in web_assets, so every card title matches without
    # each surface re-deciding — which is how this one drifted from the wiki's.
    ".dash-section-head{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;"
    "color:var(--text);}"
    ".dash-section-sub{font-size:0.85rem;font-weight:400;color:var(--muted);}"
    ".dash-items{display:flex;flex-direction:column;}"
    ".dash-item{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;"
    "padding:9px 0 9px 12px;border-inline-start:4px solid var(--border-strong);}"
    ".dash-item+.dash-item{border-top:1px solid var(--border-soft);}"
    ".dash-item--caution{border-inline-start-color:var(--caution);}"
    ".dash-item--accent{border-inline-start-color:var(--accent);}"
    ".dash-item--ok{border-inline-start-color:var(--ok);}"
    ".dash-item-main{flex:1;min-width:0;}"
    ".dash-item-title{font-weight:600;color:var(--text);}"
    ".dash-item-link{color:var(--link);text-decoration:none;border-bottom:1px dotted var(--link);}"
    ".dash-item-note{margin-top:3px;font-size:0.88rem;color:var(--muted);}"
    ".dash-chips{display:flex;flex-wrap:wrap;gap:6px;justify-content:flex-end;flex-shrink:0;}"
    ".dash-chip{font-size:0.72rem;font-weight:700;padding:2px 9px;border-radius:999px;"
    "white-space:nowrap;background:var(--chip-bg);color:var(--muted);}"
    ".dash-chip.dash-tone-caution{color:var(--caution-fg);background:var(--caution-bg);}"
    ".dash-chip.dash-tone-ok{color:var(--ok-fg);background:var(--success-bg);}"
    ".dash-chip.dash-tone-accent{color:var(--accent);}"
    # ── KPI delta ("↑1") — the third line of a stat tile.
    #    Deliberately ONE colour for both directions. Up is worse for P0 and
    #    better for 已收, and the tile does not know which it is holding; a green
    #    ↓ / red ↑ would attach a verdict the data never carried. Direction is
    #    already in the glyph, so the colour is free to stay quiet.
    ".dash-kpi-delta{display:block;margin-top:3px;font-size:0.72rem;font-weight:700;"
    "color:var(--muted);font-variant-numeric:tabular-nums;}"
    # ── Trend = the vendored report_chart SVG, themed through the brand.
    #
    #    report_chart ships its own <style> with a `prefers-color-scheme: dark`
    #    override, which is right for a standalone artifact and half-right here:
    #    BrainHub ALSO has an explicit theme toggle (`:root[data-theme=…]`), and a
    #    reader who forces dark on a light-preference machine would get a light
    #    chart in a dark card. The vendored file cannot be edited (it is
    #    byte-compared against the catalog SSoT by tests/test_brand_assets.py), so
    #    its variables are re-pointed from out here instead — the same "set the
    #    component's input, don't override its output" move the alert uses above.
    #
    #    Two hops, and the indirection is load-bearing: `--surface` and `--muted`
    #    exist on BOTH sides, so `svg.viz{--surface:var(--surface)}` would be a
    #    self-reference and resolve to nothing. The `--viz-*` aliases are read on
    #    the wrapper (where the page's values are still in scope) and consumed on
    #    the svg (where they are not shadowed).
    #
    #    Specificity: `.dash-trend svg.viz` (0,2,1) beats the embedded `svg.viz`
    #    (0,1,1) in both the base rule and the media query, so the chart follows
    #    the page in every combination of OS preference and toggle.
    #    `--viz-surface` is the CARD's background token, not the page's
    #    `--surface`. The primitive paints a full-bleed <rect> in that colour and
    #    also uses it for the surface ring on each endpoint dot; pointed at
    #    `--surface` the two matched in light mode and diverged in dark, where
    #    the card is `--color-bg-dark` and `--surface` is deep-sleep — measured
    #    as a visible navy panel sitting inside a near-black card.
    ".dash-trend{--viz-surface:var(--color-base-100);--viz-plane:var(--color-base-200);"
    "--viz-ink:var(--text);"
    "--viz-ink2:var(--muted);--viz-muted:var(--muted);--viz-grid:var(--border);"
    "--viz-axis:var(--border-strong);"
    # The 8 categorical slots map onto the shell's own --series-* tokens, which
    # carry the SAME eight hues in a different slot order and are already defined
    # for light AND dark. Matched hue-for-hue (s1→series-1, s2→series-3, …) so
    # this is a theming hop, not a re-palette.
    "--viz-s1:var(--series-1);--viz-s2:var(--series-3);--viz-s3:var(--series-4);"
    "--viz-s4:var(--series-6);--viz-s5:var(--series-7);--viz-s6:var(--series-8);"
    "--viz-s7:var(--series-5);--viz-s8:var(--series-2);"
    "margin:2px 0 2px;overflow-x:auto;}"
    ".dash-trend svg{display:block;max-width:100%;height:auto;}"
    ".dash-trend svg.viz{--surface:var(--viz-surface);--plane:var(--viz-plane);"
    "--ink:var(--viz-ink);--ink2:var(--viz-ink2);--muted:var(--viz-muted);"
    "--grid:var(--viz-grid);--axis:var(--viz-axis);"
    "--s1:var(--viz-s1);--s2:var(--viz-s2);--s3:var(--viz-s3);--s4:var(--viz-s4);"
    "--s5:var(--viz-s5);--s6:var(--viz-s6);--s7:var(--viz-s7);--s8:var(--viz-s8);}"
    # The identity channel the endpoint labels lose on a tie. Same slot order,
    # same tokens, so a swatch cannot disagree with the line it names.
    ".dash-trend-legend{display:flex;flex-wrap:wrap;gap:6px 16px;margin:4px 0 2px;"
    "font-size:0.78rem;color:var(--muted);}"
    ".dash-trend-key{display:inline-flex;align-items:center;gap:6px;}"
    ".dash-trend-swatch{width:11px;height:11px;border-radius:2px;flex:none;}"
    ".dash-trend-swatch-1{background:var(--viz-s1);}"
    ".dash-trend-swatch-2{background:var(--viz-s2);}"
    ".dash-trend-swatch-3{background:var(--viz-s3);}"
    ".dash-trend-swatch-4{background:var(--viz-s4);}"
    ".dash-trend-swatch-5{background:var(--viz-s5);}"
    ".dash-trend-swatch-6{background:var(--viz-s6);}"
    ".dash-trend-swatch-7{background:var(--viz-s7);}"
    ".dash-trend-swatch-8{background:var(--viz-s8);}"
    # The no-chart states. Same two daisyUI alert layout defaults as the
    # staleness banner: `grid-auto-flow` AND the explicit single column, because
    # `.alert:has(:nth-child(2))` re-columns any two-child alert regardless.
    ".dash-trend-empty{grid-auto-flow:row;grid-template-columns:minmax(0,1fr);"
    "justify-items:start;gap:4px;--alert-color:var(--surface);"
    "--alert-border-color:var(--border);border-inline-start:5px solid var(--border-strong);}"
    ".dash-trend-empty strong{color:var(--text);}"
    ".dash-trend-detail{font-size:0.88rem;color:var(--muted);}"
    # ── Honest-boundary rows. Same skeleton as `.dash-item` (leading state bar,
    #    hairline between rows) so the section reads as part of the same board
    #    rather than as an imported card from another system.
    ".dash-bounds{display:flex;flex-direction:column;}"
    ".dash-bound{display:flex;align-items:flex-start;gap:10px;padding:9px 0 9px 12px;"
    "border-inline-start:4px solid var(--border-strong);}"
    ".dash-bound+.dash-bound{border-top:1px solid var(--border-soft);}"
    ".dash-bound--caution{border-inline-start-color:var(--caution);}"
    ".dash-bound--ok{border-inline-start-color:var(--ok);}"
    # A floor wide enough for the WIDEST label (已量測, 3 glyphs) so all three
    # states start their text on the same x. Sized under 4.2em the two-glyph
    # 被擋 chip hit the floor and the three-glyph ones did not, and the column
    # stepped left and right down the list.
    ".dash-bound-tag{display:inline-block;flex-shrink:0;min-width:5.2em;text-align:center;}"
    ".dash-bound-main{flex:1;min-width:0;}"
    ".dash-bound-fact{font-weight:600;color:var(--text);}"
    ".dash-bound-detail{margin-top:3px;font-size:0.88rem;color:var(--muted);}"
    ".dash-bounds-close{margin-top:12px;font-size:0.86rem;color:var(--muted);"
    "--alert-color:var(--surface);--alert-border-color:var(--border);"
    "border-inline-start:5px solid var(--border-strong);}"
    ".dash-empty-row{margin:0;padding:10px 0 10px 12px;color:var(--muted);}"
    ".dash-empty h2{margin-top:0;}"
    ".dash-empty-reason{color:var(--muted);font-size:0.9rem;}"
    ".dash-empty pre{overflow-x:auto;}"
    # Five up from 640px, so the row breaks move and every divider rule above
    # has to be restated against the new geometry — the 2-up rules do not stop
    # applying just because the grid changed underneath them.
    "@media(min-width:640px){.dash-kpis{grid-template-columns:repeat(5,1fr);}"
    ".dash-kpi:not(:last-child){border-inline-end:1px dashed var(--border);}"
    ".dash-kpi:nth-child(5n){border-inline-end:none;}"
    ".dash-kpi:nth-child(n+3){border-block-start:none;}"
    ".dash-kpi:nth-child(n+6){border-block-start:1px dashed var(--border);}}"
    "</style>"
)
